### ISSUE TITLE
项目引用了com.alibaba:fastjson@1.2.44等9个开源组件，存在4个严重漏洞，建议升级

### ISSUE THREAD

**Issue by Abbykawai** [tyqinjava/stock_run#3]
大佬，看你这个项目调用了com.alibaba:fastjson@1.2.44等9个开源组件，存在4个安全漏洞，建议你升级下。
```
漏洞标题：Fastjson 1.2.25-1.2.47版本远程代码执行漏洞
漏洞编号：
漏洞描述：
Fastjson 是Java语言实现的快速JSON解析和生成器，在1.2.25-1.2.47版本中攻击者可通过精心构造的JSON请求，绕过此前修复机制，远程执行任意代码。
漏洞原因：
攻击者可通过白名单类java.lang.Class绕过checkAutotype方法，利用fastjson的cache机制引入恶意类，并调用连接远程rmi主机，通过其中的恶意类执行代码。
漏洞级别：严重
影响范围：[1.2.25, 1.2.48)
最小修复版本：1.2.48
引入路径：
analyzer:analyzer-run:1.0-SNAPSHOT:->analyzer:analyzer-run@1.0-SNAPSHOT->com.alibaba:fastjson@1.2.44
```
另外3个严重漏洞 ，信息有点多我就不贴了，你自己看下完整报告：https://www.mfsec.cn/jr?p=abaa05

**Comment by tyqinjava** [comment]
你是谁，为啥你说中文



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月25日(星期二) 中午12:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [tyqinjava/stock_run] ***@***.***等9个开源组件，存在4个严重漏洞，建议升级 (Issue #3)





 
***@***.***等9个开源组件，存在4个安全漏洞，建议你升级下。
 漏洞标题：Fastjson 1.2.25-1.2.47版本远程代码执行漏洞 漏洞编号： 漏洞描述： Fastjson 是Java语言实现的快速JSON解析和生成器，在1.2.25-1.2.47版本中攻击者可通过精心构造的JSON请求，绕过此前修复机制，远程执行任意代码。 漏洞原因： 攻击者可通过白名单类java.lang.Class绕过checkAutotype方法，利用fastjson的cache机制引入恶意类，并调用连接远程rmi主机，通过其中的恶意类执行代码。 漏洞级别：严重 影响范围：[1.2.25, 1.2.48) 最小修复版本：1.2.48 引入路径： ***@***.******@***.***  
另外3个严重漏洞 ，信息有点多我就不贴了，你自己看下完整报告：https://www.mfsec.cn/jr?p=abaa05
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Abbykawai** [comment]
嗨 您好呀，您可以修复下漏洞

**Comment by tyqinjava** [comment]
你好啊，漏洞可以修复的，你先说明的你的身份，你是机器人？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年1月26日(星期三) 下午3:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [tyqinjava/stock_run] ***@***.***等9个开源组件，存在4个严重漏洞，建议升级 (Issue #3)





 
嗨 您好呀，您可以修复下漏洞
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Abbykawai** [comment]
我当然不是机器人啦

**Comment by tyqinjava** [comment]
那你是谁，哪个公司的，微软公司？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月26日(周三) 下午4:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tyqinjava/stock_run] ***@***.***等9个开源组件，存在4个严重漏洞，建议升级 (Issue #3)




 
我当然不是机器人啦
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Abbykawai** [comment]
Hi,


加微信啊， 多交流多交流~


在2022年1月26日 ***@***.***> 写道：

那你是谁，哪个公司的，微软公司？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月26日(周三) 下午4:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tyqinjava/stock_run] ***@***.***等9个开源组件，存在4个严重漏洞，建议升级 (Issue #3)





我当然不是机器人啦

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tyqinjava** [comment]
可以啊





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月26日(周三) 下午4:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tyqinjava/stock_run] ***@***.***等9个开源组件，存在4个严重漏洞，建议升级 (Issue #3)




 Hi,
 
 
 加微信啊， 多交流多交流~
 
 
 在2022年1月26日 ***@***.***&gt; 写道：
 
 那你是谁，哪个公司的，微软公司？
 
 
 
 ---原始邮件---
 发件人: ***@***.***&amp;gt;
 发送时间: 2022年1月26日(周三) 下午4:03
 收件人: ***@***.***&amp;gt;;
 抄送: ***@***.******@***.***&amp;gt;;
 主题: Re: [tyqinjava/stock_run] ***@***.***等9个开源组件，存在4个严重漏洞，建议升级 (Issue #3)
 
 
 
 
 
 我当然不是机器人啦
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you commented.Message ID: ***@***.***&amp;gt;
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you authored the thread.Message ID: ***@***.***&gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tyqinjava** [comment]
你微信号是多少呢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月26日(周三) 下午4:16
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tyqinjava/stock_run] ***@***.***等9个开源组件，存在4个严重漏洞，建议升级 (Issue #3)




 Hi,
 
 
 加微信啊， 多交流多交流~
 
 
 在2022年1月26日 ***@***.***&gt; 写道：
 
 那你是谁，哪个公司的，微软公司？
 
 
 
 ---原始邮件---
 发件人: ***@***.***&amp;gt;
 发送时间: 2022年1月26日(周三) 下午4:03
 收件人: ***@***.***&amp;gt;;
 抄送: ***@***.******@***.***&amp;gt;;
 主题: Re: [tyqinjava/stock_run] ***@***.***等9个开源组件，存在4个严重漏洞，建议升级 (Issue #3)
 
 
 
 
 
 我当然不是机器人啦
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 Triage notifications on the go with GitHub Mobile for iOS or Android.
 You are receiving this because you commented.Message ID: ***@***.***&amp;gt;
 
 —
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you authored the thread.Message ID: ***@***.***&gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Abbykawai** [comment]
给您的qq邮箱发了邮件，请查收~

**Comment by tyqinjava** [comment]
我加了咯



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月26日(周三) 下午4:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [tyqinjava/stock_run] ***@***.***等9个开源组件，存在4个严重漏洞，建议升级 (Issue #3)




 
给您的qq邮箱发了邮件，请查收~
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zzzzail** [comment]
哈哈哈哈还聊起来了

**Comment by Abbykawai** [comment]
> 哈哈哈哈还聊起来了

官网控制台可以联系到我们😁，欢迎来聊
